import "./global.css"
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: 'Travel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body>{children}</body>
      <ToastContainer/>
    </html>
  );
}
