import "./global.css"
import { ToastContainer } from "react-toastify";
import { Experimental_CssVarsProvider as CssVarsProvider } from "@mui/material/styles";
import "react-toastify/dist/ReactToastify.css";
import { CssBaseline } from "@mui/material";
import { getInitColorSchemeScript } from "@mui/material";
import theme from "./theme";
export const metadata = {
  title: 'Travel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <CssVarsProvider theme={theme}>
        <body>
          <getInitColorSchemeScript/>
          <CssBaseline />
          {children}
          <ToastContainer />
        </body>
      </CssVarsProvider>
    </html>
  );
}
